export const filter_types = {

    SET_HIGHPRICE_STATE:'SET_HIGHPRICE_STATE',
    SET_LOWPRICE_STATE:'SET_LOWPRICE_STATE',
    SET_NEWDATE_STATE:'SET_NEWDATE_STATE',
    SET_OLDDATE_STATE:'SET_OLDDATE_STATE',
    SET_POPULARITY_STATE:'SET_POPULARITY_STATE'
}