export const ui_types = {
  SET_ISLOADING: "SET_ISLOADING",
  SET_ISLOGGEDIN: "SET_ISLOGGEDIN",
  SET_SEARCHFIELD:'SET_SEARCHFIELD',
  SET_PRODUCT_DATA:'SET_PRODUCT_DATA',
  SET_PRODUCT_DATA_STATE:'SET_PRODUCT_DATA_STATE'
};
