export const ui_types = {
  SET_ISLOADING: "SET_ISLOADING",
  SET_LOGIN_USER: "SET_LOGIN_USER",
  SET_LOGOUT_USER: "SET_LOGOUT_USER",
  SET_SEARCHFIELD: "SET_SEARCHFIELD",
  SET_PRODUCT_DATA: "SET_PRODUCT_DATA",
  SET_PRODUCT_DATA_STATE: "SET_PRODUCT_DATA_STATE",
  SET_ACCESS_TOKEN: "SET_ACCESS_TOKEN",
  SET_SNACKBAR: "SET_SNACKBAR",
  SET_MODEL_STATE:'SET_MODEL_STATE',
  SET_USER:'SET_USER'
};
