export const ui_types = {
  SET_ISLOADING: "SET_ISLOADING",
  SET_SEARCHFIELD: "SET_SEARCHFIELD",
  SET_PRODUCT_DATA: "SET_PRODUCT_DATA",
  SET_PRODUCT_DATA_STATE: "SET_PRODUCT_DATA_STATE",
  SET_SNACKBAR: "SET_SNACKBAR",
  SET_MODEL_STATE:'SET_MODEL_STATE',
  SET_USER:'SET_USER'
  SET_SUCCESS: "SET_SUCCESS",
};
